### ISSUE TITLE
Snow on leaves isn't passable

### ISSUE THREAD

**Issue by spelenza** [Team-RTG/Passable-Leaves#29] opened 2020-07-26 10:50 UTC
Unfortunately, **snow on top of leaves isn't passable**. This completely ruins the gameplay!

Snow layers should be passable too, with configurable speed (like leaves)
Same for lily pads.

**Comment by srs-bsns** [comment] 2020-07-26 10:56
Duplicate of #18

**Closed as completed by srs-bsns** 2020-07-26 10:56 UTC
Labels: duplicate, invalid

**Comment by ghost** [comment] 2021-11-28 23:54
Any resolution for this??

**Comment by srs-bsns** [comment] 2021-11-29 02:15
It was clearly stated more than 3 years ago in the other closed issue, that you also necroposted in back in Sept., why this is never going to happen.
This mod has been out of development for more than 2 1/2 years now. No sane person is still working on mods for 1.12.
