### ISSUE TITLE
X-Ray Vision when standing in leaf blocks with graphics settings set to Fast

### ISSUE THREAD

**Issue by VivianneAleksander** [Team-RTG/Passable-Leaves#30] opened 2022-03-24 12:53 UTC
Changing the Graphics setting to Fast instead of Fancy in video settings causes you to be able to see through the world while standing in leaf blocks that are adjacent to the ground. Not much of a problem in a single player world, but in multiplayer it has the chance to cause some serious issues.

**Comment by srs-bsns** [comment] 2022-03-24 13:09
Duplicate of https://github.com/Team-RTG/Passable-Leaves/issues/9#issuecomment-601541825

**Closed as completed by srs-bsns** 2022-03-24 13:09 UTC
Labels: duplicate, invalid
